import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container": "var(--color-surface-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        background: "var(--color-background)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-error": "var(--color-on-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        primary: "var(--color-primary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        error: "var(--color-error)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "error-container": "var(--color-error-container)",
        "surface-dim": "var(--color-surface-dim)",
        surface: "var(--color-surface)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-background": "var(--color-on-background)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary-container": "var(--color-secondary-container)",
        outline: "var(--color-outline)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-tint": "var(--color-surface-tint)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-surface": "var(--color-on-surface)",
        secondary: "var(--color-secondary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-error-container": "var(--color-on-error-container)",
        tertiary: "var(--color-tertiary)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "section-gap-lg": "120px",
        "container-margin-mobile": "24px",
        "section-gap-sm": "64px",
        base: "8px",
        gutter: "16px",
        "container-margin-desktop": "80px",
      },
      fontFamily: {
        display: ["var(--font-display)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "76px", letterSpacing: "-0.03em", fontWeight: "500" }],
      },
      maxWidth: {
        content: "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
