import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c8c6c2",
        "on-surface-variant": "#414943",
        "inverse-on-surface": "#f1f1ef",
        "inverse-primary": "#a1d1b4",
        "surface-container": "#eeeeec",
        "on-primary-fixed": "#002112",
        background: "#f9f9f7",
        "surface-container-low": "#f4f4f1",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e7e2d8",
        "outline-variant": "#c0c9c1",
        "on-tertiary-container": "#c9c4ba",
        "tertiary-container": "#54514a",
        "surface-container-high": "#e8e8e6",
        "on-secondary-fixed": "#1b1c19",
        primary: "#14422d",
        "primary-fixed": "#bceecf",
        "primary-container": "#2d5a43",
        "surface-container-highest": "#e2e3e0",
        "on-secondary-fixed-variant": "#474744",
        "on-primary-fixed-variant": "#224f39",
        "on-primary": "#ffffff",
        "on-primary-container": "#9fcfb2",
        error: "#ba1a1a",
        "on-secondary-container": "#63635f",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3130",
        "error-container": "#ffdad6",
        "surface-dim": "#dadad8",
        surface: "#f9f9f7",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f7",
        "surface-variant": "#e2e3e0",
        "on-tertiary-fixed": "#1d1c16",
        "on-background": "#1a1c1b",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e1dfdb",
        outline: "#717973",
        "tertiary-fixed-dim": "#cbc6bc",
        "surface-tint": "#3a674f",
        "primary-fixed-dim": "#a1d1b4",
        "secondary-fixed": "#e4e2dd",
        "on-surface": "#1a1c1b",
        secondary: "#5e5e5b",
        "on-tertiary-fixed-variant": "#49473f",
        "on-error-container": "#93000a",
        tertiary: "#3c3a33",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "section-gap-lg": "120px",
        "container-margin-mobile": "24px",
        "section-gap-sm": "64px",
        base: "8px",
        gutter: "16px",
        "container-margin-desktop": "80px",
      },
      fontFamily: {
        display: ["var(--font-display)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "76px", letterSpacing: "-0.03em", fontWeight: "500" }],
      },
      maxWidth: {
        content: "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
