/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Rosé Noir palette — mirrors web's rose theme vars
        primary:                    '#6b1e3a',
        'on-primary':               '#fbf6f4',
        'primary-container':        '#e6a8b7',
        'on-primary-container':     '#4a2530',
        'primary-fixed':            '#f5d4dc',
        'primary-fixed-dim':        '#e6a8b7',
        'inverse-primary':          '#e6a8b7',
        secondary:                  '#4a2530',
        'on-secondary':             '#fbf6f4',
        'secondary-container':      '#f0dde0',
        'on-secondary-container':   '#6e4a50',
        background:                 '#fbf6f4',
        'on-background':            '#2b1a1f',
        surface:                    '#fbf6f4',
        'surface-bright':           '#fbf6f4',
        'surface-dim':              '#e2d6d7',
        'surface-variant':          '#ebdedf',
        'on-surface':               '#2b1a1f',
        'on-surface-variant':       '#7a4f5a',
        'inverse-surface':          '#3a2a30',
        'inverse-on-surface':       '#f5e9ec',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f6ecec',
        'surface-container':        '#f0e4e5',
        'surface-container-high':   '#e9dadc',
        'surface-container-highest':'#e2d0d3',
        outline:                    '#c4a0a8',
        'outline-variant':          '#ddc0c8',
        tertiary:                   '#4a2530',
        'tertiary-container':       '#6a3a48',
        'tertiary-fixed':           '#f9e8d0',
        'on-tertiary-fixed':        '#4a2530',
        error:                      '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
      },
      fontFamily: {
        display: ['ui-serif', 'serif'],
        body:    ['system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
